config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :producers, controllers: {
    sessions:      'producers/sessions',
    registrations: 'producers/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    registrations: 'users/registrations'
  }
    resources :users
  namespace :producers do
   resources :products
   resources :maps
  end
  resources :producers do
    resource :follows, only: [:create, :destroy]
  end
  resources :products
  resources :posts do
    resource :favorites, only: [:create, :destroy]
    resource :replies, only: [:create, :destroy, :index]
  end
  namespace :users do
    resources :posts
  end
  root 'products#index'
  get 'inquiry' => 'inquiry#index'              # 入力画面
  post 'inquiry/confirm' => 'inquiry#confirm'   # 確認画面
  post 'inquiry/thanks' => 'inquiry#thanks'     # 送信完了画面
  get 'tags/:tag', to: 'producers/products#index', as: :tag
  get 'producers/products/search', to: 'producers/products#search'
  post 'producers/products/search', to: 'producers/products#search'
  get 'products/search', to: 'products#search'
  post 'products/search', to: 'products#search'
  get 'follows/create'
  get 'follows/destroy'
end

app/models/producer.rb
class Producer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :products, dependent: :destroy
  has_many :follows
  has_many :maps
  has_many :replys
  has_many :reply_posts, through: :replys, source: :post
  def followed_by?(user)
     follows.where(user_id: user.id).exists?
  end
  attachment :producer_image
end

app/controllers/producers/confirmations_controller.rb
# frozen_string_literal: true

class Producers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/producers/maps_controller.rb
class Producers::MapsController < ApplicationController
	before_action :set_map, only: [:show, :edit, :update, :destroy]

  def new
    @map = Map.new
  end
  def create
    @map = Map.new(map_params)
    @map.producer_id = current_producer.id
    @map.save
    redirect_to products_path
  end
  private
    def set_map
      @map = Map.find(params[:id])
    end
    def map_params
      params.require(:map).permit(:address, :comment, :lonlat, :producer_id)
    end
end

app/controllers/producers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Producers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/producers/passwords_controller.rb
# frozen_string_literal: true

class Producers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/producers/products_controller.rb
class Producers::ProductsController < ApplicationController
  def new
    	@product = Product.new
      @tags = ActsAsTaggableOn::Tag.all
  end
  def create
      @product = Product.new(product_params)
      @product.producer_id = current_producer.id
      @product.save
      redirect_to producers_products_path
      # エラーを見つける時に使う
      # puts @product.errors.full_messages
  end
  def show
      @product = Product.find(params[:id])
  end
  def index
      @tags = ActsAsTaggableOn::Tag.all
     if params[:tag]
      @products = Product.tagged_with(params[:tag])
     else
      @products = Product.all
     end
      @product = Product.new
      render 'products/index'
  end
  def search
      @products = Product.where("product_name LIKE ?", "%#{product_params[:product_name]}%")
      @products = @products.tagged_with(product_params[:tag_list], :match_all => false)
  end
  private
  def product_params
    params.require(:product).permit(:product_image,:producer_id, :product_name, :detail, tag_list: [])
  end
end

app/controllers/producers/registrations_controller.rb
# frozen_string_literal: true

class Producers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end
  def after_sign_out_path_for(resource)
      new_producer_session_path
  end
  def after_sign_up_path_for(resource)
      producers_products_path
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/producers/sessions_controller.rb
# frozen_string_literal: true


class Producers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end
  def after_sign_out_path_for(resource)
      new_producer_session_path
  end
  def after_sign_in_path_for(resource)
      producers_products_path
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/producers/unlocks_controller.rb
# frozen_string_literal: true

class Producers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/producers_controller.rb
class ProducersController < ApplicationController
 def show
  	  @producer = Producer.find(params[:id])
  	  @products = @producer.products
  	  @replys = @producer.replys
  	  @reply_posts= @producer.reply_posts
      @maps =@producer.maps.last(1)
      # @user = User.find(params[:id])

 end
 def edit
      @producer = Producer.find(params[:id])
 end
 def update
     @producer = Producer.find(params[:id])
     @producer.update(producer_params)
     redirect_to producer_path(@producer.id)
 end
 def index
	   @producers =Producer.all
 end
 private
 def producer_params
	params.require(:producer).permit(:producer_name, :email, :post, :a_address, :phone, :producer_image)
 end

end

app/helpers/producers_helper.rb
module ProducersHelper
end

app/views/producers/edit.html.erb
<div class="container-fluid">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
			<h3 class="ribbon4">基本情報変更</h3>
				<%= form_for(@producer) do |f| %>
				<h4>Image</h4>
				<%= f.attachment_field  :producer_image %>
			    <h5>事業者名</h5>
			    <%= f.text_field :producer_name %>

				<h5>郵便番号</h5>
				<%= f.text_field :post %>

				<h5>住所</h5>
				<%= f.text_field :a_address %>

				<h5>電話番号</h5>
				<%= f.text_field :phone %>

			    <h5>メールアドレス</h5>
			    <%= f.text_field :email %>

				<%= f.submit '基本情報を変更する' %>
			<% end %>
			<%= link_to '生産者メニューへ', producer_path(@producer) %>
		</div>
    </div>
</div>

app/views/producers/index.html.erb
<div class="container-fluid">
    <div class="row">
        <div class="col-md-3">
			<h3 class="ribbon4">全ての生産者</h3><br>
			<div>
				<img src='https://images.pexels.com/photos/532400/pexels-photo-532400.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940' width=350 />
			</div><br>
			<div>
				<img src='' width=350 />
			</div><br>
			<div>
				<img src='' width=350 />
			</div>
		</div>
        <div class="col-md-9">
        	<div class="clearfix">
				<% @producers.each do |producer| %>
					<div class="contents-item">
						<%= link_to producer_path(producer) do %>
						<%= attachment_image_tag producer, :producer_image, size: "200x150", format: 'jpeg' ,fallback: "no_image.jpg"%>
						<% end %>
						<p><%= link_to producer.producer_name, producer_path(producer.id), :class=>"button"  %></p>
						<div class="user"><%= producer.a_address %></div>
						<% if user_signed_in? %>
							<% if producer.followed_by?(current_user) %>
								<p><span></span><%=link_to "フォロー中", producer_follows_path(producer.id), method: :delete, :class=>"button"  %></p>
							<% else %>
								<p><span></span><%=link_to "フォローする", producer_follows_path(producer.id), method: :post, :class=>"button"  %></p>
								<% end %>
							<% else %>
								<div class="user"><p><span>フォロー数: </span><%= producer.follows.count %></p></div>
						<% end %>
					</div>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/producers/show.html.erb
<div class="container-fluid">
    <div class="row">
        <div class="col-md-3">
            <h3 class="ribbon4"><%= @producer.producer_name %>について</h3><br>
                  <%= attachment_image_tag @producer, :producer_image, size: "300x300", format: 'jpeg' ,fallback: "no_image.jpg"%><br>
                  <div class="user">生産者名</div>
                    <p><%= @producer.producer_name %></p>
                  <div class="user">郵便番号</div>
                      <p><%= @producer.post %></p>
                  <div class="user">住所</div>
                      <p><%= @producer.a_address %></p>
                  <div class="user">お問い合わせ先電話番号</div>
                      <p><%= @producer.phone %></p>
                  <div class="user">お問い合わせ先メールアドレス</div>
                      <p><%= @producer.email %></p>

                  <% if @producer == current_producer %>
                    <p><%= link_to "プロフィール編集", edit_producer_path(@producer), :class=>"button"   %></p>
                    <p><%= link_to '退会', producer_path(@producer), method: :delete, data: { confirm: '退会しますか？' }, :class=>"button"  %></p>
                  <% end %>
        </div>
<!--         <div class="col-md-3">
                  <h3 class="ribbon4">この生産者の周辺マップ</h3><br>
                      <% @maps.each do |map| %>
                      <P><%= map.address %>付近のマップ</P>
                      <% end %>
                  <div id="map" style="height: 300px; width: 300px;"></div>
                  <%=
                    map(:center => {
                        :latlng => [36, 140],
                        :zoom => 4,
                    })
                  %>
                <script>
                  // rubyから渡された住所配列をjsの変数に格納
                  var maps = <%= @maps.to_json.html_safe %>;

                  for(var hash_count = 0; hash_count < maps.length; hash_count++){
                    // 緯度経度とコメントを取り出しマーカー化
                    L.marker(maps[hash_count].lonlat.split(','), {icon: L.icon({iconUrl: "/marker.png"})},)
                      .bindPopup(maps[hash_count].comment)
                      .addTo(map);
                      //スケールコントロールを最大幅200px、右下、m単位で地図に追加
                      L.control.scale({ maxWidth: 200, position: 'bottomright', imperial: false }).addTo(map);

                      //地図の中心とズームレベルを指定
                      map.setView([35.40, 136], 7);

                      //地理院地図の標準地図タイル
                      var gsi =L.tileLayer('https://cyberjapandata.gsi.go.jp/xyz/std/{z}/{x}/{y}.png', 
                        {attribution: "<a href='https://maps.gsi.go.jp/development/ichiran.html' target='_blank'>地理院タイル</a>"});
                      //地理院地図の淡色地図タイル
                      var gsipale = L.tileLayer('http://cyberjapandata.gsi.go.jp/xyz/pale/{z}/{x}/{y}.png',
                        {attribution: "<a href='http://portal.cyberjapan.jp/help/termsofuse.html' target='_blank'>地理院タイル</a>"});
                      //オープンストリートマップのタイル
                      var osm = L.tileLayer('http://tile.openstreetmap.jp/{z}/{x}/{y}.png',
                        {  attribution: "<a href='http://osm.org/copyright' target='_blank'>OpenStreetMap</a> contributors" });
                      //baseMapsオブジェクトのプロパティに3つのタイルを設定
                      var baseMaps = {
                        "地理院地図" : gsi,
                        "淡色地図" : gsipale,
                        "オープンストリートマップ"  : osm
                      };
                      //layersコントロールにbaseMapsオブジェクトを設定して地図に追加
                      //コントロール内にプロパティ名が表示される
                      L.control.layers(baseMaps).addTo(map);
                      gsi.addTo(map);
                      //地図のclickイベントでonMapClick関数を呼び出し
                      map.on('click', onMapClick);
                      }
                      function onMapClick(e) {
                      //地図のclickイベント呼び出される
                      //クリック地点の座標にマーカーを追加、マーカーのclickイベントでonMarkerClick関数を呼び出し
                      var mk = L.marker(e.latlng).on('click', onMarkerClick).addTo(map);
                      }
                      function onMarkerClick(e) {
                      //マーカーのclickイベント呼び出される
                      //クリックされたマーカーを地図のレイヤから削除する
                      map.removeLayer(e.target);

                  }
                </script>
                <h3 class="ribbon4">この生産者の閲覧数：</h3>
                <p><%= number_with_delimiter(@page_views) %>PV</p>
        </div> -->
        <div class="col-md-9">
                      <h3 class="ribbon4">この生産者の商品一覧</h3><br>
                      <% @products.each do |product| %>
                      <%= attachment_image_tag product, :product_image, size: "300x300", format: 'jpeg' ,fallback: "no_image.jpg"%>
                      <dt><div class="user"><%= product.product_name %></div>
                 <details>
                   <summary>商品詳細</summary>
                    <div class="box8">
                      <dl>
                        <dt><div class="user"><%= product.product_name %></div></dt>
                        <dt><div class="user"><%= product.detail %></div></dt>
                        <dt><div class="user">この商品についているタブ
                          <p><%= raw(product.tag_list.map { |t| link_to t, tag_path(t) }.join(', ')) %></p>
                        </div></dt>
                      </dl>
                    </div>
                  </details>
                      <% end %>
<!--                   <h5>返信一覧</h5>
                          <% @replys.each do |reply| %>
                          <%= reply.comment %>
                  <% end %> -->
        </div>
    </div>
</div>