config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :producers, controllers: {
    sessions:      'producers/sessions',
    registrations: 'producers/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    registrations: 'users/registrations'
  }
    resources :users
  namespace :producers do
   resources :products
   resources :maps
  end
  resources :producers do
    resource :follows, only: [:create, :destroy]
  end
  resources :products
  resources :posts do
    resource :favorites, only: [:create, :destroy]
    resource :replies, only: [:create, :destroy, :index]
  end
  namespace :users do
    resources :posts
  end
  root 'products#index'
  get 'inquiry' => 'inquiry#index'              # 入力画面
  post 'inquiry/confirm' => 'inquiry#confirm'   # 確認画面
  post 'inquiry/thanks' => 'inquiry#thanks'     # 送信完了画面
  get 'tags/:tag', to: 'producers/products#index', as: :tag
  get 'producers/products/search', to: 'producers/products#search'
  post 'producers/products/search', to: 'producers/products#search'
  get 'products/search', to: 'products#search'
  post 'products/search', to: 'products#search'
  get 'follows/create'
  get 'follows/destroy'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
      if user.try(:admin?)
        can :access, :rails_admin
        can :manage, :all
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/follow.rb
class Follow < ApplicationRecord
    belongs_to :user
    belongs_to :producer
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
	  include ActiveModel::Model
 
  attr_accessor :name, :email, :message
 
  validates :name, :presence => {:message => '名前を入力してください'}
  validates :email, :presence => {:message => 'メールアドレスを入力してください'}
end

app/models/map.rb
class Map < ApplicationRecord
	 before_save :update_lonlat

    def update_lonlat
        lonlat = address_to_lonlat(read_attribute(:address))
        write_attribute(:lonlat, lonlat)
    end

    # 住所を保存用経緯度に変換
    def address_to_lonlat(address)
      result = Geocoder.search(address)
      lonlat = result.first.coordinates
      return lonlat.join(',')
    end
     belongs_to :producer
end

app/models/post.rb
class Post < ApplicationRecord

	belongs_to :user
	has_many :favorites
	has_many :replys
    def favorited_by?(user)
        favorites.where(user_id: user.id).exists?
    end
    def replyed_by?(producer)
        replys.where(producer_id: producer.id).exists?
    end
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
end

app/models/producer.rb
class Producer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :products, dependent: :destroy
  has_many :follows
  has_many :maps
  has_many :replys
  has_many :reply_posts, through: :replys, source: :post
  def followed_by?(user)
     follows.where(user_id: user.id).exists?
  end
  attachment :producer_image
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :producer
	acts_as_taggable
	attachment :product_image
end

app/models/reply.rb
class Reply < ApplicationRecord
	belongs_to :producer
    belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorite_posts, through: :favorites, source: :post
  has_many :follows
  has_many :follow_producers, through: :follows, source: :producer
  attachment :user_image
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
 def create
    follow = current_user.follows.build(producer_id: params[:producer_id])
    follow.save
    redirect_to producers_path
  end

  def destroy
    follow = Follow.find_by(producer_id: params[:producer_id], user_id: current_user.id)
    follow.destroy
    redirect_to producers_path
  end
end

app/controllers/inquiry_controller.rb
class InquiryController < ApplicationController
  def index
    @inquiry = Inquiry.new
    render :action => 'index'
  end

  def confirm
    @inquiry = Inquiry.new(inquiry_params)
    if @inquiry.valid?
      render :action => 'confirm'
    else
      render :action => 'index'
    end
  end

  def thanks
    @inquiry = Inquiry.new(inquiry_params)
    InquiryMailer.received_email(@inquiry).deliver
    render :action => 'thanks'
  end

  private

  def inquiry_params
    params.require(:inquiry).permit(:name, :email, :message)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def index
		@posts =Post.all
	end
	def new
	    @post = Post.new
	    @products = @producer.products.all
  	end
  	def show
    	@post = Post.find(params[:id])
    	@user = @post.user
    	@reply = current_producer.replys.build
    	@replys = @post.replys
    	# @replys = @producer.replys
  	    # @reply_posts= @producer.reply_posts
	end

  	def create
	    @post = Post.new(post_params)
	    @post.user_id = current_user.id
	    @post.save
	    redirect_to posts_path
	end
	private
	  	def post_params
	    	params.require(:post).permit(:item, :title, :description, :follow_producer, :follow_item)
	  	end
end

app/controllers/users/posts_controller.rb
class Users::PostsController < ApplicationController
	def index
		@posts =Post.all
	end
  	def new
	    @post = Post.new
	    @user = current_user
	    @producers =@user.follow_producers


  	end
  	def show
    	@post = Post.find(params[:id])
    	@user = @post.user
	end

  	def create
	    @post = Post.new(post_params)
	    @post.user_id = current_user.id
	    @post.save
	    redirect_to posts_path
	end


	private
	  	def post_params
	    	params.require(:post).permit(:item, :title, :description, :follow_producer)
	  	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	  @user = User.find(params[:id])
      @posts = @user.posts
      @favorite_posts = @user.favorite_posts
      @follow_producers = @user.follow_producers
  end
  def edit
      @user = User.find(params[:id])
  end
  def update
	    @user = User.find(params[:id])
	    @user.update(user_params)
	    redirect_to user_path(@user.id)
  end
  private
  def user_params
    params.require(:user).permit(:user_name, :email, :post, :a_address, :phone, :user_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/producers_helper.rb
module ProducersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/index.html.erb
<div class="container-fluid">
    <div class="row">
        <div class="col-md-3">
			<h3 class="ribbon4">投稿一覧</h3><br>
			<div>
			 <img src='https://images.unsplash.com/photo-1531564701487-f238224b7ce3?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=666&q=80' width=350 />
			</div>
	</div>
	<div class="col-md-9">
		<% @posts.each do |post| %>
				<%#= attachment_image_tag post.user.user_image, :user_image, :fill, 15, 15, format: 'jpeg' ,fallback: "no_image.jpg"%>
				<div class="user">
					『<%= post.user.user_name %>』さんが
					『<%= post.follow_producer %>』さんの
					『<%= post.follow_item %>』に
					『<%= post.title %>』を投稿しました。
					時間：<%= post.created_at %>
				</div>
				    <details>
				      <summary>内容について見る</summary>
					<dl>
					 <dt>
					  <div class="box8">
					   <%= post.description %>
					  </div>
					 </dt>
					</dl>
				    </details>
				    <% post.replys.each do |reply| %>
				    <details>
				      <summary>返信を見る</summary>
					<dl>
					  <dt>
					   <div class="box10">
					    <%= link_to producer_path(reply.producer_id) do %>
					     『<%= reply.producer.producer_name %>』
						<% end %>さんが返信しました
						<p>『<%= reply.comment %>』</p>
						<p>時間：<%= reply.created_at %></p>
					    </div>
					  </dt>
					</dl>
				      </details>
				      <% end %>
			<% if producer_signed_in? %>
				 <%= link_to post_path(post) do %>
					『<%= post.user.user_name %>』さんのコメントに返信
				 <% end %>
			<% end %>
			<% if user_signed_in? %>
				<% if post.favorited_by?(current_user) %> <!-- ログインしているユーザーがファボしたかどうかで分岐 -->
				<p><span></span><%=link_to "いいね！済み", post_favorites_path(post.id), method: :delete, :class=>"button"   %></p>
				<% else %>
				<p><span></span><%=link_to "いいね！する", post_favorites_path(post.id), method: :post , :class=>"button"  %></p>
					<% end %>
				<% else %>
					<p><span>お気に入り数: </span><%= post.favorites.count %></p>
			<% end %>
		<% end %>
	</div>
    </div>
</div>

app/views/posts/show.html.erb
<div class="container-fluid">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
		<% if producer_signed_in? %>
			<%= form_for([@post, @reply]) do |f| %>
			    <h3 class="ribbon4"><%= f.label :comment,"返信する" %></h3><br>
			    <%= f.text_area :comment %><br>
			  <%= f.submit %>
			<% end %>
		<% end %>
		</div>
    </div>
</div>