config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :producers, controllers: {
    sessions:      'producers/sessions',
    registrations: 'producers/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    registrations: 'users/registrations'
  }
    resources :users
  namespace :producers do
   resources :products
   resources :maps
  end
  resources :producers do
    resource :follows, only: [:create, :destroy]
  end
  resources :products
  resources :posts do
    resource :favorites, only: [:create, :destroy]
    resource :replies, only: [:create, :destroy, :index]
  end
  namespace :users do
    resources :posts
  end
  root 'products#index'
  get 'inquiry' => 'inquiry#index'              # 入力画面
  post 'inquiry/confirm' => 'inquiry#confirm'   # 確認画面
  post 'inquiry/thanks' => 'inquiry#thanks'     # 送信完了画面
  get 'tags/:tag', to: 'producers/products#index', as: :tag
  get 'producers/products/search', to: 'producers/products#search'
  post 'producers/products/search', to: 'producers/products#search'
  get 'products/search', to: 'products#search'
  post 'products/search', to: 'products#search'
  get 'follows/create'
  get 'follows/destroy'
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :producer
	acts_as_taggable
	attachment :product_image
end

app/controllers/producers/products_controller.rb
class Producers::ProductsController < ApplicationController
  def new
    	@product = Product.new
      @tags = ActsAsTaggableOn::Tag.all
  end
  def create
      @product = Product.new(product_params)
      @product.producer_id = current_producer.id
      @product.save
      redirect_to producers_products_path
      # エラーを見つける時に使う
      # puts @product.errors.full_messages
  end
  def show
      @product = Product.find(params[:id])
  end
  def index
      @tags = ActsAsTaggableOn::Tag.all
     if params[:tag]
      @products = Product.tagged_with(params[:tag])
     else
      @products = Product.all
     end
      @product = Product.new
      render 'products/index'
  end
  def search
      @products = Product.where("product_name LIKE ?", "%#{product_params[:product_name]}%")
      @products = @products.tagged_with(product_params[:tag_list], :match_all => false)
  end
  private
  def product_params
    params.require(:product).permit(:product_image,:producer_id, :product_name, :detail, tag_list: [])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
     @tags = ActsAsTaggableOn::Tag.all
     if params[:tag]
      @products = Product.tagged_with(params[:tag])
     else
      @products = Product.all
     end
      @product = Product.new
     render 'products/index'
  end
  def show
      @product = Product.find(params[:id])
  end
  def search
      @products = Product.where("product_name LIKE ?", "%#{product_params[:product_name]}%")
      @products = @products.tagged_with(product_params[:tag_list], :match_all => false)
  end
  private
	def product_params
  	params.require(:product).permit(:product_image,:producer_id, :product_name, :detail, tag_list: [])
	end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/index.html.erb
<div class="container-fluid">
    <div class="row">
        <div class="col-md-4">
            <%= form_for(@product, url: {controller: 'producers/products', action: 'search' }) do |f| %>
                <h3 class="ribbon4"><%= f.label "キーワード＋タグorタグで商品検索" %></h3><br>
                <p><%= f.text_field :product_name %></p>
                <p><%= f.submit '検索', :class=>"button"  %></p>
                <details>
                  <summary>全部のタグを出す</summary>
                    <dl>
                      <dt>
                        <div class="box8">
                          <% @tags.each do |tag| %>
                            <%= f.check_box :tag_list, { multiple: true }, "#{tag.name}", nil %>
                            <%= f.label " #{tag.name}(#{tag.taggings_count})" %>
                          <% end %>
                        </div>
                          </dt>
                        </dl>
                    </details>
            <% end %>
        </div>
        <div class="col-md-8">
          <div class="clearfix">
            <% @products.each do |product| %>
                <div class="contents-item">
                  <%= link_to product_path(product) do %>
                      <%= attachment_image_tag product, :product_image, size: "200x150", format: 'jpeg' ,fallback: "no_image.jpg"%>
                  <div class="user"><%= product.product_name %></div>
                  <% end %>
                  <details>
                    <summary>商品詳細を見る</summary>
                      <div class="box8">
                        <dl>
                          <dt>
                            <div class="user">商品名</div>
                            <p><%= product.product_name %></p>
                          </dt>
                          <dt>
                            <%= link_to producer_path(product.producer_id) do %>
                              <div class="user">生産者名</div>
                                <p><%= product.producer.producer_name %></p>
                            <% end %>
                          </dt>
                          <dt>
                           <div class="user">
                           <p>この商品についているタグ</p>
                           <p><%= raw(product.tag_list.map { |t| link_to t, tag_path(t) }.join(', ')) %></p>
                          </div>
                          </dt>
                        </dl>
                      </div>
                </details>
              </div>
            <% end %>
          </div>
        </div>
    </div>
</div>

app/views/products/serch.html.erb
<table>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.product_name %></td>
        <td><%= product.detail %></td>
        <td><%= raw(product.tag_list.map { |t| link_to t, tag_path(t) }.join(' ')) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/products/show.html.erb
<div class="container-fluid">
    <div class="row">
        <div class="col-md-4">
        	<%= attachment_image_tag @product, :product_image, size: "400x400", format: 'jpeg' ,fallback: "no_image.jpg"%>
        </div>
        <div class="col-md-8">
			<h3 class="ribbon4">商品詳細</h3><br>
			<div class="user">商品名:<%= @product.product_name %></div>
            <div class="user">生産者名：<%= @product.producer.producer_name %></div>
			<div class="user">商品概要</div>
			<div class="box8"><%= @product.detail %></div>
		</div>
    </div>
</div>